// Copyright © BEN ABT (https://benjamin-abt.com) - all rights reserved

using Unio;

namespace Unio.SourceGenerator.UnitTests;

/// <summary>A named union of string or int, generated by source generator.</summary>
[GenerateUnio]
public partial class StringOrInt : UnioBase<string, int>;

/// <summary>A named union with 3 types.</summary>
[GenerateUnio]
public partial class Result3 : UnioBase<int, string, bool>;

/// <summary>A named union with 4 types.</summary>
[GenerateUnio]
public partial class Result4 : UnioBase<int, string, bool, double>;

/// <summary>A named union with 9 types (maximum arity).</summary>
[GenerateUnio]
public partial class BigUnion : UnioBase<int, string, bool, double, long, byte, float, char, decimal>;
