// Copyright © BEN ABT (https://benjamin-abt.com) - all rights reserved

using System.Text;

namespace Unio.CodeGen;

/// <summary>
/// Code generator that produces the <c>UnioX.Generated.cs</c>, <c>UnioBase.Generated.cs</c>
/// and <c>IUnio.Generated.cs</c> source files for discriminated union types with arities
/// from <see cref="MinArity"/> to <see cref="MaxArity"/>.
/// </summary>
internal static class CodeGenerator
{
    /// <summary>The minimum number of type parameters supported by generated union types.</summary>
    public const int MinArity = 2;

    /// <summary>The maximum number of type parameters supported by generated union types.</summary>
    public const int MaxArity = 20;

    /// <summary>
    /// Generates the full C# source code for a <c>Unio&lt;T0, ..., TN&gt;</c> readonly struct
    /// with the specified <paramref name="arity"/> (number of type parameters).
    /// </summary>
    /// <param name="arity">The number of generic type parameters (2–20).</param>
    /// <returns>A string containing the complete C# source file.</returns>
    public static string GenerateUnio(int arity)
    {
        StringBuilder sb = new(4096);
        string typeParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"T{i}"));
        string structName = $"Unio<{typeParams}>";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Copyright © BEN ABT (https://benjamin-abt.com) - all rights reserved");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Unio;");
        sb.AppendLine();

        // XML doc
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Represents a discriminated union that can hold exactly one of {arity} possible types.");
        sb.AppendLine("/// Implemented as a <c>readonly struct</c> with value semantics and zero heap allocation.");
        sb.AppendLine($"/// Use <c>UnioBase&lt;{typeParams}&gt;</c> as a base class for named (class-based) union types.");
        sb.AppendLine("/// </summary>");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"/// <typeparam name=\"T{i}\">The type at index {i}.</typeparam>");
        }

        sb.AppendLine($"public readonly struct {structName} : IEquatable<{structName}>,");
        sb.AppendLine($"    IFormattable, ISpanFormattable, IUtf8SpanFormattable");
        sb.AppendLine("{");

        // Fields
        sb.AppendLine("    private readonly byte _index;");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"    private readonly T{i}? _value{i};");
        }

        sb.AppendLine();

        // Constructor
        StringBuilder ctorParams = new();
        ctorParams.Append("byte index");
        for (int i = 0; i < arity; i++)
        {
            ctorParams.Append($", T{i}? value{i} = default");
        }

        sb.AppendLine($"    private Unio({ctorParams})");
        sb.AppendLine("    {");
        sb.AppendLine("        _index = index;");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"        _value{i} = value{i};");
        }

        sb.AppendLine("    }");

        sb.AppendLine();

        // Index
        sb.AppendLine("    /// <summary>Gets the zero-based index indicating which type is currently stored.</summary>");
        sb.AppendLine("    public int Index");
        sb.AppendLine("    {");
        sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        get => _index;");
        sb.AppendLine("    }");

        sb.AppendLine();

        // IsT# properties
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"    /// <summary>Returns true if the union currently holds a value of type <typeparamref name=\"T{i}\"/>.</summary>");
            sb.AppendLine($"    public bool IsT{i}");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        get => _index == {i};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // AsT# properties
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"    /// <summary>Gets the value as <typeparamref name=\"T{i}\"/>. Throws if the union does not hold this type.</summary>");
            sb.AppendLine($"    public T{i} AsT{i}");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        get => _index == {i} ? _value{i}! : throw new InvalidOperationException($\"Cannot access T{i} when the union holds T{{_index}}.\");");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Value property
        sb.AppendLine("    /// <summary>Gets the currently stored value as an object.</summary>");
        sb.AppendLine("    public object Value");
        sb.AppendLine("    {");
        sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        get => _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => _value{i}!,");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");

        sb.AppendLine();

        // TryGetT# methods
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"    /// <summary>Attempts to get the value as <typeparamref name=\"T{i}\"/>.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public bool TryGetT{i}([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T{i} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (_index == {i}) {{ value = _value{i}!; return true; }}");
            sb.AppendLine("        value = default; return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Match<TResult>
        string matchParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<T{i}, TResult> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive match: applies the matching function based on the stored type and returns the result.</summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public TResult Match<TResult>({matchParams}) =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => whenT{i}(_value{i}!),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
        sb.AppendLine("        };");

        sb.AppendLine();

        // Match<TState, TResult>
        string matchWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<TState, T{i}, TResult> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive match with caller state to avoid delegate captures in hot paths.</summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public TResult Match<TState, TResult>(TState state, {matchWithStateParams}) =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => whenT{i}(state, _value{i}!),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
        sb.AppendLine("        };");

        sb.AppendLine();

        // Switch
        string switchParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Action<T{i}> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive switch: executes the matching action based on the stored type.</summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public void Switch({switchParams})");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (_index)");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            case {i}: whenT{i}(_value{i}!); break;");
        }

        sb.AppendLine("            default: throw new InvalidOperationException(\"Invalid union state.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();

        // Switch<TState>
        string switchWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Action<TState, T{i}> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive switch with caller state to avoid delegate captures in hot paths.</summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public void Switch<TState>(TState state, {switchWithStateParams})");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (_index)");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            case {i}: whenT{i}(state, _value{i}!); break;");
        }

        sb.AppendLine("            default: throw new InvalidOperationException(\"Invalid union state.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();

        // MatchAsync (Task)
        string matchAsyncParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<T{i}, Task<TResult>> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive async match: applies the matching async function based on the stored type and returns the result.</summary>");
        sb.AppendLine($"    public Task<TResult> MatchAsync<TResult>({matchAsyncParams}) =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => whenT{i}(_value{i}!),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
        sb.AppendLine("        };");

        sb.AppendLine();

        // MatchAsync<TState, TResult>
        string matchAsyncWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<TState, T{i}, Task<TResult>> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive async match with caller state to avoid delegate captures in hot paths.</summary>");
        sb.AppendLine($"    public Task<TResult> MatchAsync<TState, TResult>(TState state, {matchAsyncWithStateParams}) =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => whenT{i}(state, _value{i}!),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
        sb.AppendLine("        };");

        sb.AppendLine();

        // SwitchAsync (Task)
        string switchAsyncParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<T{i}, Task> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive async switch: executes the matching async action based on the stored type.</summary>");
        sb.AppendLine($"    public Task SwitchAsync({switchAsyncParams}) =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => whenT{i}(_value{i}!),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
        sb.AppendLine("        };");

        sb.AppendLine();

        // SwitchAsync<TState>
        string switchAsyncWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<TState, T{i}, Task> whenT{i}"));
        sb.AppendLine("    /// <summary>Exhaustive async switch with caller state to avoid delegate captures in hot paths.</summary>");
        sb.AppendLine($"    public Task SwitchAsync<TState>(TState state, {switchAsyncWithStateParams}) =>");
        sb.AppendLine("        _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => whenT{i}(state, _value{i}!),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
        sb.AppendLine("        };");

        sb.AppendLine();

        // Implicit operators
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"    /// <summary>Creates a union holding a value of type <typeparamref name=\"T{i}\"/>.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static implicit operator {structName}(T{i} value) => new({i}, value{i}: value);");
            sb.AppendLine();
        }

        // MapT# methods
        for (int i = 0; i < arity; i++)
        {
            string[] mapTypeParamsList = Enumerable.Range(0, arity).Select(j => j == i ? "TNew" : $"T{j}").ToArray();
            string mapReturnType = $"Unio<{string.Join(", ", mapTypeParamsList)}>";
            sb.AppendLine($"    /// <summary>Transforms the value at index {i} using the specified mapping function, returning a new union.</summary>");
            sb.AppendLine($"    public {mapReturnType} MapT{i}<TNew>(Func<T{i}, TNew> map) =>");
            sb.AppendLine("        _index switch");
            sb.AppendLine("        {");
            for (int j = 0; j < arity; j++)
            {
                if (j == i)
                {
                    sb.AppendLine($"            {j} => ({mapReturnType})map(_value{j}!),");
                }
                else
                {
                    sb.AppendLine($"            {j} => ({mapReturnType})_value{j}!,");
                }
            }
            sb.AppendLine("            _ => throw new InvalidOperationException(\"Invalid union state.\")");
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // ValueOrT# methods
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"    /// <summary>Gets the value at index {i} or returns the specified fallback.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public T{i} ValueOrT{i}(T{i} fallback) => _index == {i} ? _value{i}! : fallback;");
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Gets the value at index {i} or invokes the factory to create a fallback.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public T{i} ValueOrT{i}(Func<T{i}> factory) => _index == {i} ? _value{i}! : factory();");
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Gets the value at index {i} or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public T{i} ValueOrT{i}<TState>(TState state, Func<TState, T{i}> factory) => _index == {i} ? _value{i}! : factory(state);");
            sb.AppendLine();
        }

        // Equals(T) - struct: parameter is non-nullable (IEquatable<T> for value types)
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public bool Equals({structName} other) =>");
        sb.AppendLine("        _index == other._index && _index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            {i} => EqualityComparer<T{i}>.Default.Equals(_value{i}, other._value{i}),");
        }

        sb.AppendLine("            _ => false");
        sb.AppendLine("        };");

        sb.AppendLine();

        // Equals(object)
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public override bool Equals(object? obj) => obj is {structName} other && Equals(other);");

        sb.AppendLine();

        // GetHashCode – lighter mixing: (index * 397) ^ valueHash avoids the full
        // HashCode.Combine overhead (struct init + two Add calls) while still
        // discriminating equal values at different indices.
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        unchecked");
        sb.AppendLine("        {");
        sb.AppendLine("            return (_index * 397) ^ (_index switch");
        sb.AppendLine("            {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"                {i} => EqualityComparer<T{i}>.Default.GetHashCode(_value{i}!),");
        }

        sb.AppendLine("                _ => 0");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();

        // Equality operators
        sb.AppendLine("    /// <summary>Equality operator.</summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static bool operator ==({structName} left, {structName} right) => left.Equals(right);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inequality operator.</summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static bool operator !=({structName} left, {structName} right) => !left.Equals(right);");

        sb.AppendLine();

        // ToString
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public override string ToString() => _index switch");
        sb.AppendLine("    {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"        {i} => _value{i}?.ToString() ?? string.Empty,");
        }

        sb.AppendLine("        _ => string.Empty");
        sb.AppendLine("    };");

        sb.AppendLine();

        // IFormattable.ToString
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public string ToString(string? format, IFormatProvider? formatProvider) => _index switch");
        sb.AppendLine("    {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"        {i} => _value{i} is IFormattable f{i} ? f{i}.ToString(format, formatProvider) : _value{i}?.ToString() ?? string.Empty,");
        }

        sb.AppendLine("        _ => string.Empty");
        sb.AppendLine("    };");

        sb.AppendLine();

        // ISpanFormattable.TryFormat
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (_index)");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            case {i}:");
            sb.AppendLine($"                if (_value{i} is ISpanFormattable sf{i}) return sf{i}.TryFormat(destination, out charsWritten, format, provider);");
            sb.AppendLine("                break;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        string s = ToString();");
        sb.AppendLine("        if (s.AsSpan().TryCopyTo(destination)) { charsWritten = s.Length; return true; }");
        sb.AppendLine("        charsWritten = 0; return false;");
        sb.AppendLine("    }");

        sb.AppendLine();

        // IUtf8SpanFormattable.TryFormat
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (_index)");
        sb.AppendLine("        {");
        for (int i = 0; i < arity; i++)
        {
            sb.AppendLine($"            case {i}:");
            sb.AppendLine($"                if (_value{i} is IUtf8SpanFormattable uf{i}) return uf{i}.TryFormat(utf8Destination, out bytesWritten, format, provider);");
            sb.AppendLine("                break;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        string s = ToString();");
        sb.AppendLine("        int byteCount = System.Text.Encoding.UTF8.GetByteCount(s);");
        sb.AppendLine("        if (byteCount <= utf8Destination.Length) { bytesWritten = System.Text.Encoding.UTF8.GetBytes(s, utf8Destination); return true; }");
        sb.AppendLine("        bytesWritten = 0; return false;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a single <c>UnioBase.Generated.cs</c> file containing abstract base classes
    /// <c>UnioBase&lt;T0, ..., TN&gt;</c> for all supported arities. These classes wrap the
    /// corresponding <c>Unio&lt;...&gt;</c> readonly structs and serve as base types for
    /// named discriminated unions generated by the Roslyn source generator.
    /// </summary>
    /// <returns>A string containing the complete C# source file with all base classes.</returns>
    public static string GenerateUnioBase()
    {
        StringBuilder sb = new(65536);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Copyright © BEN ABT (https://benjamin-abt.com) - all rights reserved");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Unio;");
        sb.AppendLine();

        for (int arity = MinArity; arity <= MaxArity; arity++)
        {
            string typeParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"T{i}"));
            string unioType = $"Unio<{typeParams}>";
            string baseName = $"UnioBase<{typeParams}>";

            // XML doc
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Abstract base class for named discriminated unions with {arity} type parameters.");
            sb.AppendLine($"/// Wraps <c>{unioType.Replace("<", "&lt;", StringComparison.Ordinal).Replace(">", "&gt;", StringComparison.Ordinal)}</c> and exposes all union operations.");
            sb.AppendLine("/// Use this as a base class for source-generated named union types.");
            sb.AppendLine("/// </summary>");
            for (int i = 0; i < arity; i++)
            {
                sb.AppendLine($"/// <typeparam name=\"T{i}\">The type at index {i}.</typeparam>");
            }

            sb.AppendLine($"public abstract class {baseName} : IEquatable<{baseName}>,");
            sb.AppendLine($"    IFormattable, ISpanFormattable, IUtf8SpanFormattable");
            sb.AppendLine("{");

            // Protected union field
            sb.AppendLine($"    /// <summary>The underlying readonly struct holding the discriminated value.</summary>");
            sb.AppendLine($"    protected readonly {unioType} _union;");
            sb.AppendLine();

            // Protected constructor
            sb.AppendLine($"    /// <summary>Initializes a new instance with the given <paramref name=\"union\"/> value.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    protected {baseName.Split('<')[0]}({unioType} union) => _union = union;");
            sb.AppendLine();

            // Index
            sb.AppendLine("    /// <summary>Gets the zero-based index indicating which type is currently stored.</summary>");
            sb.AppendLine("    public int Index");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        get => _union.Index;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Value
            sb.AppendLine("    /// <summary>Gets the currently stored value as an object.</summary>");
            sb.AppendLine("    public object Value");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        get => _union.Value;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // IsT# / AsT# / TryGetT# per type
            for (int i = 0; i < arity; i++)
            {
                // IsT#
                sb.AppendLine($"    /// <summary>Returns true if the union currently holds a value of type <typeparamref name=\"T{i}\"/>.</summary>");
                sb.AppendLine($"    public bool IsT{i}");
                sb.AppendLine("    {");
                sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        get => _union.IsT{i};");
                sb.AppendLine("    }");
                sb.AppendLine();

                // AsT#
                sb.AppendLine($"    /// <summary>Gets the value as <typeparamref name=\"T{i}\"/>. Throws if the union does not hold this type.</summary>");
                sb.AppendLine($"    public T{i} AsT{i}");
                sb.AppendLine("    {");
                sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        get => _union.AsT{i};");
                sb.AppendLine("    }");
                sb.AppendLine();

                // TryGetT#
                sb.AppendLine($"    /// <summary>Attempts to get the value as <typeparamref name=\"T{i}\"/>.</summary>");
                sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"    public bool TryGetT{i}([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T{i} value) => _union.TryGetT{i}(out value);");
                sb.AppendLine();
            }

            // Match<TResult>
            string matchParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<T{i}, TResult> whenT{i}"));
            string matchArgs = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive match: applies the matching function based on the stored type and returns the result.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public TResult Match<TResult>({matchParams}) => _union.Match({matchArgs});");
            sb.AppendLine();

            // Match<TState, TResult>
            string matchWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<TState, T{i}, TResult> whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive match with caller state to avoid delegate captures in hot paths.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public TResult Match<TState, TResult>(TState state, {matchWithStateParams}) => _union.Match(state, {matchArgs});");
            sb.AppendLine();

            // Switch
            string switchParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Action<T{i}> whenT{i}"));
            string switchArgs = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive switch: executes the matching action based on the stored type.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public void Switch({switchParams}) => _union.Switch({switchArgs});");
            sb.AppendLine();

            // Switch<TState>
            string switchWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Action<TState, T{i}> whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive switch with caller state to avoid delegate captures in hot paths.</summary>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public void Switch<TState>(TState state, {switchWithStateParams}) => _union.Switch(state, {switchArgs});");
            sb.AppendLine();

            // MatchAsync
            string matchAsyncParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<T{i}, Task<TResult>> whenT{i}"));
            string matchAsyncArgs = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive async match: applies the matching async function based on the stored type and returns the result.</summary>");
            sb.AppendLine($"    public Task<TResult> MatchAsync<TResult>({matchAsyncParams}) => _union.MatchAsync({matchAsyncArgs});");
            sb.AppendLine();

            // MatchAsync<TState, TResult>
            string matchAsyncWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<TState, T{i}, Task<TResult>> whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive async match with caller state to avoid delegate captures in hot paths.</summary>");
            sb.AppendLine($"    public Task<TResult> MatchAsync<TState, TResult>(TState state, {matchAsyncWithStateParams}) => _union.MatchAsync(state, {matchAsyncArgs});");
            sb.AppendLine();

            // SwitchAsync
            string switchAsyncParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<T{i}, Task> whenT{i}"));
            string switchAsyncArgs = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive async switch: executes the matching async action based on the stored type.</summary>");
            sb.AppendLine($"    public Task SwitchAsync({switchAsyncParams}) => _union.SwitchAsync({switchAsyncArgs});");
            sb.AppendLine();

            // SwitchAsync<TState>
            string switchAsyncWithStateParams = string.Join(", ", Enumerable.Range(0, arity).Select(i => $"Func<TState, T{i}, Task> whenT{i}"));
            sb.AppendLine("    /// <summary>Exhaustive async switch with caller state to avoid delegate captures in hot paths.</summary>");
            sb.AppendLine($"    public Task SwitchAsync<TState>(TState state, {switchAsyncWithStateParams}) => _union.SwitchAsync(state, {switchAsyncArgs});");
            sb.AppendLine();

            // MapT# - returns struct types, not base class (by design)
            for (int i = 0; i < arity; i++)
            {
                string[] mapTypes = Enumerable.Range(0, arity).Select(j => j == i ? "TNew" : $"T{j}").ToArray();
                string mapReturn = $"Unio<{string.Join(", ", mapTypes)}>";
                string mapReturnXml = mapReturn.Replace("<", "&lt;", StringComparison.Ordinal).Replace(">", "&gt;", StringComparison.Ordinal);
                sb.AppendLine($"    /// <summary>Transforms the value at index {i} using the specified mapping function, returning a new <c>{mapReturnXml}</c>.</summary>");
                sb.AppendLine($"    public {mapReturn} MapT{i}<TNew>(Func<T{i}, TNew> map) => _union.MapT{i}(map);");
                sb.AppendLine();
            }

            // ValueOrT# methods
            for (int i = 0; i < arity; i++)
            {
                sb.AppendLine($"    /// <summary>Gets the value at index {i} or returns the specified fallback.</summary>");
                sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"    public T{i} ValueOrT{i}(T{i} fallback) => _union.ValueOrT{i}(fallback);");
                sb.AppendLine();
                sb.AppendLine($"    /// <summary>Gets the value at index {i} or invokes the factory to create a fallback.</summary>");
                sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"    public T{i} ValueOrT{i}(Func<T{i}> factory) => _union.ValueOrT{i}(factory);");
                sb.AppendLine();
                sb.AppendLine($"    /// <summary>Gets the value at index {i} or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>");
                sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"    public T{i} ValueOrT{i}<TState>(TState state, Func<TState, T{i}> factory) => _union.ValueOrT{i}(state, factory);");
                sb.AppendLine();
            }

            // Equals(UnioBase<...>?)
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public bool Equals({baseName}? other) => other is not null && _union.Equals(other._union);");
            sb.AppendLine();

            // Equals(object?)
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public override bool Equals(object? obj) => obj is {baseName} other && Equals(other);");
            sb.AppendLine();

            // GetHashCode
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    public override int GetHashCode() => _union.GetHashCode();");
            sb.AppendLine();

            // ToString
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    public override string ToString() => _union.ToString();");
            sb.AppendLine();

            // IFormattable.ToString
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    public string ToString(string? format, IFormatProvider? formatProvider) => _union.ToString(format, formatProvider);");
            sb.AppendLine();

            // ISpanFormattable.TryFormat
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) => _union.TryFormat(destination, out charsWritten, format, provider);");
            sb.AppendLine();

            // IUtf8SpanFormattable.TryFormat
            sb.AppendLine("    /// <inheritdoc/>");
            sb.AppendLine("    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider) => _union.TryFormat(utf8Destination, out bytesWritten, format, provider);");

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
