// <auto-generated/>
// Copyright © BEN ABT (https://benjamin-abt.com) - all rights reserved

#nullable enable

namespace Unio;

/// <summary>
/// Represents a discriminated union that can hold exactly one of 14 possible types.
/// Implemented as a <c>readonly struct</c> with value semantics and zero heap allocation.
/// Use <c>UnioBase&lt;T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13&gt;</c> as a base class for named (class-based) union types.
/// </summary>
/// <typeparam name="T0">The type at index 0.</typeparam>
/// <typeparam name="T1">The type at index 1.</typeparam>
/// <typeparam name="T2">The type at index 2.</typeparam>
/// <typeparam name="T3">The type at index 3.</typeparam>
/// <typeparam name="T4">The type at index 4.</typeparam>
/// <typeparam name="T5">The type at index 5.</typeparam>
/// <typeparam name="T6">The type at index 6.</typeparam>
/// <typeparam name="T7">The type at index 7.</typeparam>
/// <typeparam name="T8">The type at index 8.</typeparam>
/// <typeparam name="T9">The type at index 9.</typeparam>
/// <typeparam name="T10">The type at index 10.</typeparam>
/// <typeparam name="T11">The type at index 11.</typeparam>
/// <typeparam name="T12">The type at index 12.</typeparam>
/// <typeparam name="T13">The type at index 13.</typeparam>
public readonly struct Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> : IEquatable<Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>>,
    IFormattable, ISpanFormattable, IUtf8SpanFormattable
{
    private readonly byte _index;
    private readonly T0? _value0;
    private readonly T1? _value1;
    private readonly T2? _value2;
    private readonly T3? _value3;
    private readonly T4? _value4;
    private readonly T5? _value5;
    private readonly T6? _value6;
    private readonly T7? _value7;
    private readonly T8? _value8;
    private readonly T9? _value9;
    private readonly T10? _value10;
    private readonly T11? _value11;
    private readonly T12? _value12;
    private readonly T13? _value13;

    private Unio(byte index, T0? value0 = default, T1? value1 = default, T2? value2 = default, T3? value3 = default, T4? value4 = default, T5? value5 = default, T6? value6 = default, T7? value7 = default, T8? value8 = default, T9? value9 = default, T10? value10 = default, T11? value11 = default, T12? value12 = default, T13? value13 = default)
    {
        _index = index;
        _value0 = value0;
        _value1 = value1;
        _value2 = value2;
        _value3 = value3;
        _value4 = value4;
        _value5 = value5;
        _value6 = value6;
        _value7 = value7;
        _value8 = value8;
        _value9 = value9;
        _value10 = value10;
        _value11 = value11;
        _value12 = value12;
        _value13 = value13;
    }

    /// <summary>Gets the zero-based index indicating which type is currently stored.</summary>
    public int Index
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T0"/>.</summary>
    public bool IsT0
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 0;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T1"/>.</summary>
    public bool IsT1
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 1;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T2"/>.</summary>
    public bool IsT2
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 2;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T3"/>.</summary>
    public bool IsT3
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 3;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T4"/>.</summary>
    public bool IsT4
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 4;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T5"/>.</summary>
    public bool IsT5
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 5;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T6"/>.</summary>
    public bool IsT6
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 6;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T7"/>.</summary>
    public bool IsT7
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 7;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T8"/>.</summary>
    public bool IsT8
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 8;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T9"/>.</summary>
    public bool IsT9
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 9;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T10"/>.</summary>
    public bool IsT10
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 10;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T11"/>.</summary>
    public bool IsT11
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 11;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T12"/>.</summary>
    public bool IsT12
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 12;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T13"/>.</summary>
    public bool IsT13
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 13;
    }

    /// <summary>Gets the value as <typeparamref name="T0"/>. Throws if the union does not hold this type.</summary>
    public T0 AsT0
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 0 ? _value0! : throw new InvalidOperationException($"Cannot access T0 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T1"/>. Throws if the union does not hold this type.</summary>
    public T1 AsT1
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 1 ? _value1! : throw new InvalidOperationException($"Cannot access T1 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T2"/>. Throws if the union does not hold this type.</summary>
    public T2 AsT2
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 2 ? _value2! : throw new InvalidOperationException($"Cannot access T2 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T3"/>. Throws if the union does not hold this type.</summary>
    public T3 AsT3
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 3 ? _value3! : throw new InvalidOperationException($"Cannot access T3 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T4"/>. Throws if the union does not hold this type.</summary>
    public T4 AsT4
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 4 ? _value4! : throw new InvalidOperationException($"Cannot access T4 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T5"/>. Throws if the union does not hold this type.</summary>
    public T5 AsT5
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 5 ? _value5! : throw new InvalidOperationException($"Cannot access T5 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T6"/>. Throws if the union does not hold this type.</summary>
    public T6 AsT6
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 6 ? _value6! : throw new InvalidOperationException($"Cannot access T6 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T7"/>. Throws if the union does not hold this type.</summary>
    public T7 AsT7
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 7 ? _value7! : throw new InvalidOperationException($"Cannot access T7 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T8"/>. Throws if the union does not hold this type.</summary>
    public T8 AsT8
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 8 ? _value8! : throw new InvalidOperationException($"Cannot access T8 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T9"/>. Throws if the union does not hold this type.</summary>
    public T9 AsT9
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 9 ? _value9! : throw new InvalidOperationException($"Cannot access T9 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T10"/>. Throws if the union does not hold this type.</summary>
    public T10 AsT10
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 10 ? _value10! : throw new InvalidOperationException($"Cannot access T10 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T11"/>. Throws if the union does not hold this type.</summary>
    public T11 AsT11
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 11 ? _value11! : throw new InvalidOperationException($"Cannot access T11 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T12"/>. Throws if the union does not hold this type.</summary>
    public T12 AsT12
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 12 ? _value12! : throw new InvalidOperationException($"Cannot access T12 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T13"/>. Throws if the union does not hold this type.</summary>
    public T13 AsT13
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 13 ? _value13! : throw new InvalidOperationException($"Cannot access T13 when the union holds T{_index}.");
    }

    /// <summary>Gets the currently stored value as an object.</summary>
    public object Value
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
    }

    /// <summary>Attempts to get the value as <typeparamref name="T0"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT0([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 value)
    {
        if (_index == 0) { value = _value0!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T1"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT1([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T1 value)
    {
        if (_index == 1) { value = _value1!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T2"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT2([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T2 value)
    {
        if (_index == 2) { value = _value2!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T3"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT3([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T3 value)
    {
        if (_index == 3) { value = _value3!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T4"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT4([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T4 value)
    {
        if (_index == 4) { value = _value4!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T5"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT5([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T5 value)
    {
        if (_index == 5) { value = _value5!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T6"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT6([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T6 value)
    {
        if (_index == 6) { value = _value6!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T7"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT7([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T7 value)
    {
        if (_index == 7) { value = _value7!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T8"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT8([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T8 value)
    {
        if (_index == 8) { value = _value8!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T9"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT9([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T9 value)
    {
        if (_index == 9) { value = _value9!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T10"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT10([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T10 value)
    {
        if (_index == 10) { value = _value10!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T11"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT11([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T11 value)
    {
        if (_index == 11) { value = _value11!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T12"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT12([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T12 value)
    {
        if (_index == 12) { value = _value12!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T13"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT13([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T13 value)
    {
        if (_index == 13) { value = _value13!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T0"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT0([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 value, out Unio<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 0) { value = _value0!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T1"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT1([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T1 value, out Unio<T0, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 1) { value = _value1!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T2"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT2([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T2 value, out Unio<T0, T1, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 2) { value = _value2!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T3"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT3([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T3 value, out Unio<T0, T1, T2, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 3) { value = _value3!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T4"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT4([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T4 value, out Unio<T0, T1, T2, T3, T5, T6, T7, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 4) { value = _value4!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T5"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT5([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T5 value, out Unio<T0, T1, T2, T3, T4, T6, T7, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 5) { value = _value5!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T6"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT6([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T6 value, out Unio<T0, T1, T2, T3, T4, T5, T7, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 6) { value = _value6!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T7"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT7([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T7 value, out Unio<T0, T1, T2, T3, T4, T5, T6, T8, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 7) { value = _value7!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T8"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT8([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T8 value, out Unio<T0, T1, T2, T3, T4, T5, T6, T7, T9, T10, T11, T12, T13> remainder)
    {
        if (_index == 8) { value = _value8!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T9"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT9([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T9 value, out Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T10, T11, T12, T13> remainder)
    {
        if (_index == 9) { value = _value9!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T10"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT10([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T10 value, out Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T11, T12, T13> remainder)
    {
        if (_index == 10) { value = _value10!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            11 => _value11!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T11"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT11([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T11 value, out Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T12, T13> remainder)
    {
        if (_index == 11) { value = _value11!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            12 => _value12!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T12"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT12([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T12 value, out Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T13> remainder)
    {
        if (_index == 12) { value = _value12!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            13 => _value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T13"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT13([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T13 value, out Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> remainder)
    {
        if (_index == 13) { value = _value13!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            7 => _value7!,
            8 => _value8!,
            9 => _value9!,
            10 => _value10!,
            11 => _value11!,
            12 => _value12!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Exhaustive match: applies the matching function based on the stored type and returns the result.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public TResult Match<TResult>(Func<T0, TResult> whenT0, Func<T1, TResult> whenT1, Func<T2, TResult> whenT2, Func<T3, TResult> whenT3, Func<T4, TResult> whenT4, Func<T5, TResult> whenT5, Func<T6, TResult> whenT6, Func<T7, TResult> whenT7, Func<T8, TResult> whenT8, Func<T9, TResult> whenT9, Func<T10, TResult> whenT10, Func<T11, TResult> whenT11, Func<T12, TResult> whenT12, Func<T13, TResult> whenT13) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            4 => whenT4(_value4!),
            5 => whenT5(_value5!),
            6 => whenT6(_value6!),
            7 => whenT7(_value7!),
            8 => whenT8(_value8!),
            9 => whenT9(_value9!),
            10 => whenT10(_value10!),
            11 => whenT11(_value11!),
            12 => whenT12(_value12!),
            13 => whenT13(_value13!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive match with caller state to avoid delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public TResult Match<TState, TResult>(TState state, Func<TState, T0, TResult> whenT0, Func<TState, T1, TResult> whenT1, Func<TState, T2, TResult> whenT2, Func<TState, T3, TResult> whenT3, Func<TState, T4, TResult> whenT4, Func<TState, T5, TResult> whenT5, Func<TState, T6, TResult> whenT6, Func<TState, T7, TResult> whenT7, Func<TState, T8, TResult> whenT8, Func<TState, T9, TResult> whenT9, Func<TState, T10, TResult> whenT10, Func<TState, T11, TResult> whenT11, Func<TState, T12, TResult> whenT12, Func<TState, T13, TResult> whenT13) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            4 => whenT4(state, _value4!),
            5 => whenT5(state, _value5!),
            6 => whenT6(state, _value6!),
            7 => whenT7(state, _value7!),
            8 => whenT8(state, _value8!),
            9 => whenT9(state, _value9!),
            10 => whenT10(state, _value10!),
            11 => whenT11(state, _value11!),
            12 => whenT12(state, _value12!),
            13 => whenT13(state, _value13!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive switch: executes the matching action based on the stored type.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Switch(Action<T0> whenT0, Action<T1> whenT1, Action<T2> whenT2, Action<T3> whenT3, Action<T4> whenT4, Action<T5> whenT5, Action<T6> whenT6, Action<T7> whenT7, Action<T8> whenT8, Action<T9> whenT9, Action<T10> whenT10, Action<T11> whenT11, Action<T12> whenT12, Action<T13> whenT13)
    {
        switch (_index)
        {
            case 0: whenT0(_value0!); break;
            case 1: whenT1(_value1!); break;
            case 2: whenT2(_value2!); break;
            case 3: whenT3(_value3!); break;
            case 4: whenT4(_value4!); break;
            case 5: whenT5(_value5!); break;
            case 6: whenT6(_value6!); break;
            case 7: whenT7(_value7!); break;
            case 8: whenT8(_value8!); break;
            case 9: whenT9(_value9!); break;
            case 10: whenT10(_value10!); break;
            case 11: whenT11(_value11!); break;
            case 12: whenT12(_value12!); break;
            case 13: whenT13(_value13!); break;
            default: throw new InvalidOperationException("Invalid union state.");
        }
    }

    /// <summary>Exhaustive switch with caller state to avoid delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Switch<TState>(TState state, Action<TState, T0> whenT0, Action<TState, T1> whenT1, Action<TState, T2> whenT2, Action<TState, T3> whenT3, Action<TState, T4> whenT4, Action<TState, T5> whenT5, Action<TState, T6> whenT6, Action<TState, T7> whenT7, Action<TState, T8> whenT8, Action<TState, T9> whenT9, Action<TState, T10> whenT10, Action<TState, T11> whenT11, Action<TState, T12> whenT12, Action<TState, T13> whenT13)
    {
        switch (_index)
        {
            case 0: whenT0(state, _value0!); break;
            case 1: whenT1(state, _value1!); break;
            case 2: whenT2(state, _value2!); break;
            case 3: whenT3(state, _value3!); break;
            case 4: whenT4(state, _value4!); break;
            case 5: whenT5(state, _value5!); break;
            case 6: whenT6(state, _value6!); break;
            case 7: whenT7(state, _value7!); break;
            case 8: whenT8(state, _value8!); break;
            case 9: whenT9(state, _value9!); break;
            case 10: whenT10(state, _value10!); break;
            case 11: whenT11(state, _value11!); break;
            case 12: whenT12(state, _value12!); break;
            case 13: whenT13(state, _value13!); break;
            default: throw new InvalidOperationException("Invalid union state.");
        }
    }

    /// <summary>Exhaustive async match: applies the matching async function based on the stored type and returns the result.</summary>
    public Task<TResult> Match<TResult>(Func<T0, Task<TResult>> whenT0, Func<T1, Task<TResult>> whenT1, Func<T2, Task<TResult>> whenT2, Func<T3, Task<TResult>> whenT3, Func<T4, Task<TResult>> whenT4, Func<T5, Task<TResult>> whenT5, Func<T6, Task<TResult>> whenT6, Func<T7, Task<TResult>> whenT7, Func<T8, Task<TResult>> whenT8, Func<T9, Task<TResult>> whenT9, Func<T10, Task<TResult>> whenT10, Func<T11, Task<TResult>> whenT11, Func<T12, Task<TResult>> whenT12, Func<T13, Task<TResult>> whenT13) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            4 => whenT4(_value4!),
            5 => whenT5(_value5!),
            6 => whenT6(_value6!),
            7 => whenT7(_value7!),
            8 => whenT8(_value8!),
            9 => whenT9(_value9!),
            10 => whenT10(_value10!),
            11 => whenT11(_value11!),
            12 => whenT12(_value12!),
            13 => whenT13(_value13!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async match with caller state to avoid delegate captures in hot paths.</summary>
    public Task<TResult> Match<TState, TResult>(TState state, Func<TState, T0, Task<TResult>> whenT0, Func<TState, T1, Task<TResult>> whenT1, Func<TState, T2, Task<TResult>> whenT2, Func<TState, T3, Task<TResult>> whenT3, Func<TState, T4, Task<TResult>> whenT4, Func<TState, T5, Task<TResult>> whenT5, Func<TState, T6, Task<TResult>> whenT6, Func<TState, T7, Task<TResult>> whenT7, Func<TState, T8, Task<TResult>> whenT8, Func<TState, T9, Task<TResult>> whenT9, Func<TState, T10, Task<TResult>> whenT10, Func<TState, T11, Task<TResult>> whenT11, Func<TState, T12, Task<TResult>> whenT12, Func<TState, T13, Task<TResult>> whenT13) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            4 => whenT4(state, _value4!),
            5 => whenT5(state, _value5!),
            6 => whenT6(state, _value6!),
            7 => whenT7(state, _value7!),
            8 => whenT8(state, _value8!),
            9 => whenT9(state, _value9!),
            10 => whenT10(state, _value10!),
            11 => whenT11(state, _value11!),
            12 => whenT12(state, _value12!),
            13 => whenT13(state, _value13!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async switch: executes the matching async action based on the stored type.</summary>
    public Task Switch(Func<T0, Task> whenT0, Func<T1, Task> whenT1, Func<T2, Task> whenT2, Func<T3, Task> whenT3, Func<T4, Task> whenT4, Func<T5, Task> whenT5, Func<T6, Task> whenT6, Func<T7, Task> whenT7, Func<T8, Task> whenT8, Func<T9, Task> whenT9, Func<T10, Task> whenT10, Func<T11, Task> whenT11, Func<T12, Task> whenT12, Func<T13, Task> whenT13) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            4 => whenT4(_value4!),
            5 => whenT5(_value5!),
            6 => whenT6(_value6!),
            7 => whenT7(_value7!),
            8 => whenT8(_value8!),
            9 => whenT9(_value9!),
            10 => whenT10(_value10!),
            11 => whenT11(_value11!),
            12 => whenT12(_value12!),
            13 => whenT13(_value13!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async switch with caller state to avoid delegate captures in hot paths.</summary>
    public Task Switch<TState>(TState state, Func<TState, T0, Task> whenT0, Func<TState, T1, Task> whenT1, Func<TState, T2, Task> whenT2, Func<TState, T3, Task> whenT3, Func<TState, T4, Task> whenT4, Func<TState, T5, Task> whenT5, Func<TState, T6, Task> whenT6, Func<TState, T7, Task> whenT7, Func<TState, T8, Task> whenT8, Func<TState, T9, Task> whenT9, Func<TState, T10, Task> whenT10, Func<TState, T11, Task> whenT11, Func<TState, T12, Task> whenT12, Func<TState, T13, Task> whenT13) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            4 => whenT4(state, _value4!),
            5 => whenT5(state, _value5!),
            6 => whenT6(state, _value6!),
            7 => whenT7(state, _value7!),
            8 => whenT8(state, _value8!),
            9 => whenT9(state, _value9!),
            10 => whenT10(state, _value10!),
            11 => whenT11(state, _value11!),
            12 => whenT12(state, _value12!),
            13 => whenT13(state, _value13!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Creates a union holding a value of type <typeparamref name="T0"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T0 value) => new(0, value0: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T1"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T1 value) => new(1, value1: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T2"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T2 value) => new(2, value2: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T3"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T3 value) => new(3, value3: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T4"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T4 value) => new(4, value4: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T5"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T5 value) => new(5, value5: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T6"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T6 value) => new(6, value6: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T7"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T7 value) => new(7, value7: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T8"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T8 value) => new(8, value8: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T9"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T9 value) => new(9, value9: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T10"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T10 value) => new(10, value10: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T11"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T11 value) => new(11, value11: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T12"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T12 value) => new(12, value12: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T13"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T13 value) => new(13, value13: value);

    /// <summary>Transforms the value at index 0 using the specified mapping function, returning a new union.</summary>
    public Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> MapT0<TNew>(Func<T0, TNew> map) =>
        _index switch
        {
            0 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)map(_value0!),
            1 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<TNew, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 1 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> MapT1<TNew>(Func<T1, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)map(_value1!),
            2 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, TNew, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 2 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> MapT2<TNew>(Func<T2, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)map(_value2!),
            3 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, TNew, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 3 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> MapT3<TNew>(Func<T3, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)map(_value3!),
            4 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, TNew, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 4 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13> MapT4<TNew>(Func<T4, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)map(_value4!),
            5 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, TNew, T5, T6, T7, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 5 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13> MapT5<TNew>(Func<T5, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)map(_value5!),
            6 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, TNew, T6, T7, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 6 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13> MapT6<TNew>(Func<T6, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)map(_value6!),
            7 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, T5, TNew, T7, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 7 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13> MapT7<TNew>(Func<T7, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)map(_value7!),
            8 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, T5, T6, TNew, T8, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 8 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13> MapT8<TNew>(Func<T8, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)map(_value8!),
            9 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, TNew, T9, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 9 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13> MapT9<TNew>(Func<T9, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)map(_value9!),
            10 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, TNew, T10, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 10 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13> MapT10<TNew>(Func<T10, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)map(_value10!),
            11 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TNew, T11, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 11 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13> MapT11<TNew>(Func<T11, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)map(_value11!),
            12 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TNew, T12, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 12 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13> MapT12<TNew>(Func<T12, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)map(_value12!),
            13 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TNew, T13>)_value13!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 13 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew> MapT13<TNew>(Func<T13, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value6!,
            7 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value7!,
            8 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value8!,
            9 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value9!,
            10 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value10!,
            11 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value11!,
            12 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)_value12!,
            13 => (Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TNew>)map(_value13!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Gets the value at index 0 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0(T0 fallback) => _index == 0 ? _value0! : fallback;

    /// <summary>Gets the value at index 0 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0(Func<T0> factory) => _index == 0 ? _value0! : factory();

    /// <summary>Gets the value at index 0 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0<TState>(TState state, Func<TState, T0> factory) => _index == 0 ? _value0! : factory(state);

    /// <summary>Gets the value at index 1 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1(T1 fallback) => _index == 1 ? _value1! : fallback;

    /// <summary>Gets the value at index 1 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1(Func<T1> factory) => _index == 1 ? _value1! : factory();

    /// <summary>Gets the value at index 1 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1<TState>(TState state, Func<TState, T1> factory) => _index == 1 ? _value1! : factory(state);

    /// <summary>Gets the value at index 2 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2(T2 fallback) => _index == 2 ? _value2! : fallback;

    /// <summary>Gets the value at index 2 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2(Func<T2> factory) => _index == 2 ? _value2! : factory();

    /// <summary>Gets the value at index 2 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2<TState>(TState state, Func<TState, T2> factory) => _index == 2 ? _value2! : factory(state);

    /// <summary>Gets the value at index 3 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3(T3 fallback) => _index == 3 ? _value3! : fallback;

    /// <summary>Gets the value at index 3 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3(Func<T3> factory) => _index == 3 ? _value3! : factory();

    /// <summary>Gets the value at index 3 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3<TState>(TState state, Func<TState, T3> factory) => _index == 3 ? _value3! : factory(state);

    /// <summary>Gets the value at index 4 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T4 ValueOrT4(T4 fallback) => _index == 4 ? _value4! : fallback;

    /// <summary>Gets the value at index 4 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T4 ValueOrT4(Func<T4> factory) => _index == 4 ? _value4! : factory();

    /// <summary>Gets the value at index 4 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T4 ValueOrT4<TState>(TState state, Func<TState, T4> factory) => _index == 4 ? _value4! : factory(state);

    /// <summary>Gets the value at index 5 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T5 ValueOrT5(T5 fallback) => _index == 5 ? _value5! : fallback;

    /// <summary>Gets the value at index 5 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T5 ValueOrT5(Func<T5> factory) => _index == 5 ? _value5! : factory();

    /// <summary>Gets the value at index 5 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T5 ValueOrT5<TState>(TState state, Func<TState, T5> factory) => _index == 5 ? _value5! : factory(state);

    /// <summary>Gets the value at index 6 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T6 ValueOrT6(T6 fallback) => _index == 6 ? _value6! : fallback;

    /// <summary>Gets the value at index 6 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T6 ValueOrT6(Func<T6> factory) => _index == 6 ? _value6! : factory();

    /// <summary>Gets the value at index 6 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T6 ValueOrT6<TState>(TState state, Func<TState, T6> factory) => _index == 6 ? _value6! : factory(state);

    /// <summary>Gets the value at index 7 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T7 ValueOrT7(T7 fallback) => _index == 7 ? _value7! : fallback;

    /// <summary>Gets the value at index 7 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T7 ValueOrT7(Func<T7> factory) => _index == 7 ? _value7! : factory();

    /// <summary>Gets the value at index 7 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T7 ValueOrT7<TState>(TState state, Func<TState, T7> factory) => _index == 7 ? _value7! : factory(state);

    /// <summary>Gets the value at index 8 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T8 ValueOrT8(T8 fallback) => _index == 8 ? _value8! : fallback;

    /// <summary>Gets the value at index 8 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T8 ValueOrT8(Func<T8> factory) => _index == 8 ? _value8! : factory();

    /// <summary>Gets the value at index 8 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T8 ValueOrT8<TState>(TState state, Func<TState, T8> factory) => _index == 8 ? _value8! : factory(state);

    /// <summary>Gets the value at index 9 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T9 ValueOrT9(T9 fallback) => _index == 9 ? _value9! : fallback;

    /// <summary>Gets the value at index 9 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T9 ValueOrT9(Func<T9> factory) => _index == 9 ? _value9! : factory();

    /// <summary>Gets the value at index 9 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T9 ValueOrT9<TState>(TState state, Func<TState, T9> factory) => _index == 9 ? _value9! : factory(state);

    /// <summary>Gets the value at index 10 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T10 ValueOrT10(T10 fallback) => _index == 10 ? _value10! : fallback;

    /// <summary>Gets the value at index 10 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T10 ValueOrT10(Func<T10> factory) => _index == 10 ? _value10! : factory();

    /// <summary>Gets the value at index 10 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T10 ValueOrT10<TState>(TState state, Func<TState, T10> factory) => _index == 10 ? _value10! : factory(state);

    /// <summary>Gets the value at index 11 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T11 ValueOrT11(T11 fallback) => _index == 11 ? _value11! : fallback;

    /// <summary>Gets the value at index 11 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T11 ValueOrT11(Func<T11> factory) => _index == 11 ? _value11! : factory();

    /// <summary>Gets the value at index 11 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T11 ValueOrT11<TState>(TState state, Func<TState, T11> factory) => _index == 11 ? _value11! : factory(state);

    /// <summary>Gets the value at index 12 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T12 ValueOrT12(T12 fallback) => _index == 12 ? _value12! : fallback;

    /// <summary>Gets the value at index 12 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T12 ValueOrT12(Func<T12> factory) => _index == 12 ? _value12! : factory();

    /// <summary>Gets the value at index 12 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T12 ValueOrT12<TState>(TState state, Func<TState, T12> factory) => _index == 12 ? _value12! : factory(state);

    /// <summary>Gets the value at index 13 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T13 ValueOrT13(T13 fallback) => _index == 13 ? _value13! : fallback;

    /// <summary>Gets the value at index 13 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T13 ValueOrT13(Func<T13> factory) => _index == 13 ? _value13! : factory();

    /// <summary>Gets the value at index 13 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T13 ValueOrT13<TState>(TState state, Func<TState, T13> factory) => _index == 13 ? _value13! : factory(state);

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool Equals(Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> other) =>
        _index == other._index && _index switch
        {
            0 => EqualityComparer<T0>.Default.Equals(_value0, other._value0),
            1 => EqualityComparer<T1>.Default.Equals(_value1, other._value1),
            2 => EqualityComparer<T2>.Default.Equals(_value2, other._value2),
            3 => EqualityComparer<T3>.Default.Equals(_value3, other._value3),
            4 => EqualityComparer<T4>.Default.Equals(_value4, other._value4),
            5 => EqualityComparer<T5>.Default.Equals(_value5, other._value5),
            6 => EqualityComparer<T6>.Default.Equals(_value6, other._value6),
            7 => EqualityComparer<T7>.Default.Equals(_value7, other._value7),
            8 => EqualityComparer<T8>.Default.Equals(_value8, other._value8),
            9 => EqualityComparer<T9>.Default.Equals(_value9, other._value9),
            10 => EqualityComparer<T10>.Default.Equals(_value10, other._value10),
            11 => EqualityComparer<T11>.Default.Equals(_value11, other._value11),
            12 => EqualityComparer<T12>.Default.Equals(_value12, other._value12),
            13 => EqualityComparer<T13>.Default.Equals(_value13, other._value13),
            _ => false
        };

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object? obj) => obj is Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> other && Equals(other);

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode()
    {
        unchecked
        {
            return (_index * 397) ^ (_index switch
            {
                0 => EqualityComparer<T0>.Default.GetHashCode(_value0!),
                1 => EqualityComparer<T1>.Default.GetHashCode(_value1!),
                2 => EqualityComparer<T2>.Default.GetHashCode(_value2!),
                3 => EqualityComparer<T3>.Default.GetHashCode(_value3!),
                4 => EqualityComparer<T4>.Default.GetHashCode(_value4!),
                5 => EqualityComparer<T5>.Default.GetHashCode(_value5!),
                6 => EqualityComparer<T6>.Default.GetHashCode(_value6!),
                7 => EqualityComparer<T7>.Default.GetHashCode(_value7!),
                8 => EqualityComparer<T8>.Default.GetHashCode(_value8!),
                9 => EqualityComparer<T9>.Default.GetHashCode(_value9!),
                10 => EqualityComparer<T10>.Default.GetHashCode(_value10!),
                11 => EqualityComparer<T11>.Default.GetHashCode(_value11!),
                12 => EqualityComparer<T12>.Default.GetHashCode(_value12!),
                13 => EqualityComparer<T13>.Default.GetHashCode(_value13!),
                _ => 0
            });
        }
    }

    /// <summary>Equality operator.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> left, Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> right) => left.Equals(right);

    /// <summary>Inequality operator.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> left, Unio<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> right) => !left.Equals(right);

    /// <inheritdoc/>
    public override string ToString() => _index switch
    {
        0 => _value0?.ToString() ?? string.Empty,
        1 => _value1?.ToString() ?? string.Empty,
        2 => _value2?.ToString() ?? string.Empty,
        3 => _value3?.ToString() ?? string.Empty,
        4 => _value4?.ToString() ?? string.Empty,
        5 => _value5?.ToString() ?? string.Empty,
        6 => _value6?.ToString() ?? string.Empty,
        7 => _value7?.ToString() ?? string.Empty,
        8 => _value8?.ToString() ?? string.Empty,
        9 => _value9?.ToString() ?? string.Empty,
        10 => _value10?.ToString() ?? string.Empty,
        11 => _value11?.ToString() ?? string.Empty,
        12 => _value12?.ToString() ?? string.Empty,
        13 => _value13?.ToString() ?? string.Empty,
        _ => string.Empty
    };

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => _index switch
    {
        0 => _value0 is IFormattable f0 ? f0.ToString(format, formatProvider) : _value0?.ToString() ?? string.Empty,
        1 => _value1 is IFormattable f1 ? f1.ToString(format, formatProvider) : _value1?.ToString() ?? string.Empty,
        2 => _value2 is IFormattable f2 ? f2.ToString(format, formatProvider) : _value2?.ToString() ?? string.Empty,
        3 => _value3 is IFormattable f3 ? f3.ToString(format, formatProvider) : _value3?.ToString() ?? string.Empty,
        4 => _value4 is IFormattable f4 ? f4.ToString(format, formatProvider) : _value4?.ToString() ?? string.Empty,
        5 => _value5 is IFormattable f5 ? f5.ToString(format, formatProvider) : _value5?.ToString() ?? string.Empty,
        6 => _value6 is IFormattable f6 ? f6.ToString(format, formatProvider) : _value6?.ToString() ?? string.Empty,
        7 => _value7 is IFormattable f7 ? f7.ToString(format, formatProvider) : _value7?.ToString() ?? string.Empty,
        8 => _value8 is IFormattable f8 ? f8.ToString(format, formatProvider) : _value8?.ToString() ?? string.Empty,
        9 => _value9 is IFormattable f9 ? f9.ToString(format, formatProvider) : _value9?.ToString() ?? string.Empty,
        10 => _value10 is IFormattable f10 ? f10.ToString(format, formatProvider) : _value10?.ToString() ?? string.Empty,
        11 => _value11 is IFormattable f11 ? f11.ToString(format, formatProvider) : _value11?.ToString() ?? string.Empty,
        12 => _value12 is IFormattable f12 ? f12.ToString(format, formatProvider) : _value12?.ToString() ?? string.Empty,
        13 => _value13 is IFormattable f13 ? f13.ToString(format, formatProvider) : _value13?.ToString() ?? string.Empty,
        _ => string.Empty
    };

    /// <inheritdoc/>
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        switch (_index)
        {
            case 0:
                if (_value0 is ISpanFormattable sf0) return sf0.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 1:
                if (_value1 is ISpanFormattable sf1) return sf1.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 2:
                if (_value2 is ISpanFormattable sf2) return sf2.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 3:
                if (_value3 is ISpanFormattable sf3) return sf3.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 4:
                if (_value4 is ISpanFormattable sf4) return sf4.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 5:
                if (_value5 is ISpanFormattable sf5) return sf5.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 6:
                if (_value6 is ISpanFormattable sf6) return sf6.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 7:
                if (_value7 is ISpanFormattable sf7) return sf7.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 8:
                if (_value8 is ISpanFormattable sf8) return sf8.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 9:
                if (_value9 is ISpanFormattable sf9) return sf9.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 10:
                if (_value10 is ISpanFormattable sf10) return sf10.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 11:
                if (_value11 is ISpanFormattable sf11) return sf11.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 12:
                if (_value12 is ISpanFormattable sf12) return sf12.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 13:
                if (_value13 is ISpanFormattable sf13) return sf13.TryFormat(destination, out charsWritten, format, provider);
                break;
        }
        string s = ToString();
        if (s.AsSpan().TryCopyTo(destination)) { charsWritten = s.Length; return true; }
        charsWritten = 0; return false;
    }

    /// <inheritdoc/>
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        switch (_index)
        {
            case 0:
                if (_value0 is IUtf8SpanFormattable uf0) return uf0.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 1:
                if (_value1 is IUtf8SpanFormattable uf1) return uf1.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 2:
                if (_value2 is IUtf8SpanFormattable uf2) return uf2.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 3:
                if (_value3 is IUtf8SpanFormattable uf3) return uf3.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 4:
                if (_value4 is IUtf8SpanFormattable uf4) return uf4.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 5:
                if (_value5 is IUtf8SpanFormattable uf5) return uf5.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 6:
                if (_value6 is IUtf8SpanFormattable uf6) return uf6.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 7:
                if (_value7 is IUtf8SpanFormattable uf7) return uf7.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 8:
                if (_value8 is IUtf8SpanFormattable uf8) return uf8.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 9:
                if (_value9 is IUtf8SpanFormattable uf9) return uf9.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 10:
                if (_value10 is IUtf8SpanFormattable uf10) return uf10.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 11:
                if (_value11 is IUtf8SpanFormattable uf11) return uf11.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 12:
                if (_value12 is IUtf8SpanFormattable uf12) return uf12.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 13:
                if (_value13 is IUtf8SpanFormattable uf13) return uf13.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
        }
        string s = ToString();
        int byteCount = System.Text.Encoding.UTF8.GetByteCount(s);
        if (byteCount <= utf8Destination.Length) { bytesWritten = System.Text.Encoding.UTF8.GetBytes(s, utf8Destination); return true; }
        bytesWritten = 0; return false;
    }
}
