// <auto-generated/>
// Copyright © BEN ABT (https://benjamin-abt.com) - all rights reserved

#nullable enable

namespace Unio;

/// <summary>
/// Represents a discriminated union that can hold exactly one of 7 possible types.
/// Implemented as a <c>readonly struct</c> with value semantics and zero heap allocation.
/// Use <c>UnioBase&lt;T0, T1, T2, T3, T4, T5, T6&gt;</c> as a base class for named (class-based) union types.
/// </summary>
/// <typeparam name="T0">The type at index 0.</typeparam>
/// <typeparam name="T1">The type at index 1.</typeparam>
/// <typeparam name="T2">The type at index 2.</typeparam>
/// <typeparam name="T3">The type at index 3.</typeparam>
/// <typeparam name="T4">The type at index 4.</typeparam>
/// <typeparam name="T5">The type at index 5.</typeparam>
/// <typeparam name="T6">The type at index 6.</typeparam>
public readonly struct Unio<T0, T1, T2, T3, T4, T5, T6> : IEquatable<Unio<T0, T1, T2, T3, T4, T5, T6>>,
    IFormattable, ISpanFormattable, IUtf8SpanFormattable
{
    private readonly byte _index;
    private readonly T0? _value0;
    private readonly T1? _value1;
    private readonly T2? _value2;
    private readonly T3? _value3;
    private readonly T4? _value4;
    private readonly T5? _value5;
    private readonly T6? _value6;

    private Unio(byte index, T0? value0 = default, T1? value1 = default, T2? value2 = default, T3? value3 = default, T4? value4 = default, T5? value5 = default, T6? value6 = default)
    {
        _index = index;
        _value0 = value0;
        _value1 = value1;
        _value2 = value2;
        _value3 = value3;
        _value4 = value4;
        _value5 = value5;
        _value6 = value6;
    }

    /// <summary>Gets the zero-based index indicating which type is currently stored.</summary>
    public int Index
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T0"/>.</summary>
    public bool IsT0
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 0;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T1"/>.</summary>
    public bool IsT1
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 1;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T2"/>.</summary>
    public bool IsT2
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 2;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T3"/>.</summary>
    public bool IsT3
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 3;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T4"/>.</summary>
    public bool IsT4
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 4;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T5"/>.</summary>
    public bool IsT5
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 5;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T6"/>.</summary>
    public bool IsT6
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 6;
    }

    /// <summary>Gets the value as <typeparamref name="T0"/>. Throws if the union does not hold this type.</summary>
    public T0 AsT0
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 0 ? _value0! : throw new InvalidOperationException($"Cannot access T0 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T1"/>. Throws if the union does not hold this type.</summary>
    public T1 AsT1
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 1 ? _value1! : throw new InvalidOperationException($"Cannot access T1 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T2"/>. Throws if the union does not hold this type.</summary>
    public T2 AsT2
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 2 ? _value2! : throw new InvalidOperationException($"Cannot access T2 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T3"/>. Throws if the union does not hold this type.</summary>
    public T3 AsT3
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 3 ? _value3! : throw new InvalidOperationException($"Cannot access T3 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T4"/>. Throws if the union does not hold this type.</summary>
    public T4 AsT4
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 4 ? _value4! : throw new InvalidOperationException($"Cannot access T4 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T5"/>. Throws if the union does not hold this type.</summary>
    public T5 AsT5
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 5 ? _value5! : throw new InvalidOperationException($"Cannot access T5 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T6"/>. Throws if the union does not hold this type.</summary>
    public T6 AsT6
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 6 ? _value6! : throw new InvalidOperationException($"Cannot access T6 when the union holds T{_index}.");
    }

    /// <summary>Gets the currently stored value as an object.</summary>
    public object Value
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            4 => _value4!,
            5 => _value5!,
            6 => _value6!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
    }

    /// <summary>Attempts to get the value as <typeparamref name="T0"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT0([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 value)
    {
        if (_index == 0) { value = _value0!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T1"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT1([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T1 value)
    {
        if (_index == 1) { value = _value1!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T2"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT2([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T2 value)
    {
        if (_index == 2) { value = _value2!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T3"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT3([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T3 value)
    {
        if (_index == 3) { value = _value3!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T4"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT4([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T4 value)
    {
        if (_index == 4) { value = _value4!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T5"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT5([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T5 value)
    {
        if (_index == 5) { value = _value5!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T6"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT6([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T6 value)
    {
        if (_index == 6) { value = _value6!; return true; }
        value = default; return false;
    }

    /// <summary>Exhaustive match: applies the matching function based on the stored type and returns the result.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public TResult Match<TResult>(Func<T0, TResult> whenT0, Func<T1, TResult> whenT1, Func<T2, TResult> whenT2, Func<T3, TResult> whenT3, Func<T4, TResult> whenT4, Func<T5, TResult> whenT5, Func<T6, TResult> whenT6) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            4 => whenT4(_value4!),
            5 => whenT5(_value5!),
            6 => whenT6(_value6!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive match with caller state to avoid delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public TResult Match<TState, TResult>(TState state, Func<TState, T0, TResult> whenT0, Func<TState, T1, TResult> whenT1, Func<TState, T2, TResult> whenT2, Func<TState, T3, TResult> whenT3, Func<TState, T4, TResult> whenT4, Func<TState, T5, TResult> whenT5, Func<TState, T6, TResult> whenT6) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            4 => whenT4(state, _value4!),
            5 => whenT5(state, _value5!),
            6 => whenT6(state, _value6!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive switch: executes the matching action based on the stored type.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Switch(Action<T0> whenT0, Action<T1> whenT1, Action<T2> whenT2, Action<T3> whenT3, Action<T4> whenT4, Action<T5> whenT5, Action<T6> whenT6)
    {
        switch (_index)
        {
            case 0: whenT0(_value0!); break;
            case 1: whenT1(_value1!); break;
            case 2: whenT2(_value2!); break;
            case 3: whenT3(_value3!); break;
            case 4: whenT4(_value4!); break;
            case 5: whenT5(_value5!); break;
            case 6: whenT6(_value6!); break;
            default: throw new InvalidOperationException("Invalid union state.");
        }
    }

    /// <summary>Exhaustive switch with caller state to avoid delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Switch<TState>(TState state, Action<TState, T0> whenT0, Action<TState, T1> whenT1, Action<TState, T2> whenT2, Action<TState, T3> whenT3, Action<TState, T4> whenT4, Action<TState, T5> whenT5, Action<TState, T6> whenT6)
    {
        switch (_index)
        {
            case 0: whenT0(state, _value0!); break;
            case 1: whenT1(state, _value1!); break;
            case 2: whenT2(state, _value2!); break;
            case 3: whenT3(state, _value3!); break;
            case 4: whenT4(state, _value4!); break;
            case 5: whenT5(state, _value5!); break;
            case 6: whenT6(state, _value6!); break;
            default: throw new InvalidOperationException("Invalid union state.");
        }
    }

    /// <summary>Exhaustive async match: applies the matching async function based on the stored type and returns the result.</summary>
    public Task<TResult> MatchAsync<TResult>(Func<T0, Task<TResult>> whenT0, Func<T1, Task<TResult>> whenT1, Func<T2, Task<TResult>> whenT2, Func<T3, Task<TResult>> whenT3, Func<T4, Task<TResult>> whenT4, Func<T5, Task<TResult>> whenT5, Func<T6, Task<TResult>> whenT6) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            4 => whenT4(_value4!),
            5 => whenT5(_value5!),
            6 => whenT6(_value6!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async match with caller state to avoid delegate captures in hot paths.</summary>
    public Task<TResult> MatchAsync<TState, TResult>(TState state, Func<TState, T0, Task<TResult>> whenT0, Func<TState, T1, Task<TResult>> whenT1, Func<TState, T2, Task<TResult>> whenT2, Func<TState, T3, Task<TResult>> whenT3, Func<TState, T4, Task<TResult>> whenT4, Func<TState, T5, Task<TResult>> whenT5, Func<TState, T6, Task<TResult>> whenT6) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            4 => whenT4(state, _value4!),
            5 => whenT5(state, _value5!),
            6 => whenT6(state, _value6!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async switch: executes the matching async action based on the stored type.</summary>
    public Task SwitchAsync(Func<T0, Task> whenT0, Func<T1, Task> whenT1, Func<T2, Task> whenT2, Func<T3, Task> whenT3, Func<T4, Task> whenT4, Func<T5, Task> whenT5, Func<T6, Task> whenT6) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            4 => whenT4(_value4!),
            5 => whenT5(_value5!),
            6 => whenT6(_value6!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async switch with caller state to avoid delegate captures in hot paths.</summary>
    public Task SwitchAsync<TState>(TState state, Func<TState, T0, Task> whenT0, Func<TState, T1, Task> whenT1, Func<TState, T2, Task> whenT2, Func<TState, T3, Task> whenT3, Func<TState, T4, Task> whenT4, Func<TState, T5, Task> whenT5, Func<TState, T6, Task> whenT6) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            4 => whenT4(state, _value4!),
            5 => whenT5(state, _value5!),
            6 => whenT6(state, _value6!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Creates a union holding a value of type <typeparamref name="T0"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6>(T0 value) => new(0, value0: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T1"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6>(T1 value) => new(1, value1: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T2"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6>(T2 value) => new(2, value2: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T3"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6>(T3 value) => new(3, value3: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T4"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6>(T4 value) => new(4, value4: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T5"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6>(T5 value) => new(5, value5: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T6"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3, T4, T5, T6>(T6 value) => new(6, value6: value);

    /// <summary>Transforms the value at index 0 using the specified mapping function, returning a new union.</summary>
    public Unio<TNew, T1, T2, T3, T4, T5, T6> MapT0<TNew>(Func<T0, TNew> map) =>
        _index switch
        {
            0 => (Unio<TNew, T1, T2, T3, T4, T5, T6>)map(_value0!),
            1 => (Unio<TNew, T1, T2, T3, T4, T5, T6>)_value1!,
            2 => (Unio<TNew, T1, T2, T3, T4, T5, T6>)_value2!,
            3 => (Unio<TNew, T1, T2, T3, T4, T5, T6>)_value3!,
            4 => (Unio<TNew, T1, T2, T3, T4, T5, T6>)_value4!,
            5 => (Unio<TNew, T1, T2, T3, T4, T5, T6>)_value5!,
            6 => (Unio<TNew, T1, T2, T3, T4, T5, T6>)_value6!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 1 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, TNew, T2, T3, T4, T5, T6> MapT1<TNew>(Func<T1, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, TNew, T2, T3, T4, T5, T6>)_value0!,
            1 => (Unio<T0, TNew, T2, T3, T4, T5, T6>)map(_value1!),
            2 => (Unio<T0, TNew, T2, T3, T4, T5, T6>)_value2!,
            3 => (Unio<T0, TNew, T2, T3, T4, T5, T6>)_value3!,
            4 => (Unio<T0, TNew, T2, T3, T4, T5, T6>)_value4!,
            5 => (Unio<T0, TNew, T2, T3, T4, T5, T6>)_value5!,
            6 => (Unio<T0, TNew, T2, T3, T4, T5, T6>)_value6!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 2 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, TNew, T3, T4, T5, T6> MapT2<TNew>(Func<T2, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, TNew, T3, T4, T5, T6>)_value0!,
            1 => (Unio<T0, T1, TNew, T3, T4, T5, T6>)_value1!,
            2 => (Unio<T0, T1, TNew, T3, T4, T5, T6>)map(_value2!),
            3 => (Unio<T0, T1, TNew, T3, T4, T5, T6>)_value3!,
            4 => (Unio<T0, T1, TNew, T3, T4, T5, T6>)_value4!,
            5 => (Unio<T0, T1, TNew, T3, T4, T5, T6>)_value5!,
            6 => (Unio<T0, T1, TNew, T3, T4, T5, T6>)_value6!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 3 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, TNew, T4, T5, T6> MapT3<TNew>(Func<T3, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, TNew, T4, T5, T6>)_value0!,
            1 => (Unio<T0, T1, T2, TNew, T4, T5, T6>)_value1!,
            2 => (Unio<T0, T1, T2, TNew, T4, T5, T6>)_value2!,
            3 => (Unio<T0, T1, T2, TNew, T4, T5, T6>)map(_value3!),
            4 => (Unio<T0, T1, T2, TNew, T4, T5, T6>)_value4!,
            5 => (Unio<T0, T1, T2, TNew, T4, T5, T6>)_value5!,
            6 => (Unio<T0, T1, T2, TNew, T4, T5, T6>)_value6!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 4 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, TNew, T5, T6> MapT4<TNew>(Func<T4, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, TNew, T5, T6>)_value0!,
            1 => (Unio<T0, T1, T2, T3, TNew, T5, T6>)_value1!,
            2 => (Unio<T0, T1, T2, T3, TNew, T5, T6>)_value2!,
            3 => (Unio<T0, T1, T2, T3, TNew, T5, T6>)_value3!,
            4 => (Unio<T0, T1, T2, T3, TNew, T5, T6>)map(_value4!),
            5 => (Unio<T0, T1, T2, T3, TNew, T5, T6>)_value5!,
            6 => (Unio<T0, T1, T2, T3, TNew, T5, T6>)_value6!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 5 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, TNew, T6> MapT5<TNew>(Func<T5, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, TNew, T6>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, TNew, T6>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, TNew, T6>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, TNew, T6>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, TNew, T6>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, TNew, T6>)map(_value5!),
            6 => (Unio<T0, T1, T2, T3, T4, TNew, T6>)_value6!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 6 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, T3, T4, T5, TNew> MapT6<TNew>(Func<T6, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, T3, T4, T5, TNew>)_value0!,
            1 => (Unio<T0, T1, T2, T3, T4, T5, TNew>)_value1!,
            2 => (Unio<T0, T1, T2, T3, T4, T5, TNew>)_value2!,
            3 => (Unio<T0, T1, T2, T3, T4, T5, TNew>)_value3!,
            4 => (Unio<T0, T1, T2, T3, T4, T5, TNew>)_value4!,
            5 => (Unio<T0, T1, T2, T3, T4, T5, TNew>)_value5!,
            6 => (Unio<T0, T1, T2, T3, T4, T5, TNew>)map(_value6!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Gets the value at index 0 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0(T0 fallback) => _index == 0 ? _value0! : fallback;

    /// <summary>Gets the value at index 0 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0(Func<T0> factory) => _index == 0 ? _value0! : factory();

    /// <summary>Gets the value at index 0 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0<TState>(TState state, Func<TState, T0> factory) => _index == 0 ? _value0! : factory(state);

    /// <summary>Gets the value at index 1 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1(T1 fallback) => _index == 1 ? _value1! : fallback;

    /// <summary>Gets the value at index 1 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1(Func<T1> factory) => _index == 1 ? _value1! : factory();

    /// <summary>Gets the value at index 1 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1<TState>(TState state, Func<TState, T1> factory) => _index == 1 ? _value1! : factory(state);

    /// <summary>Gets the value at index 2 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2(T2 fallback) => _index == 2 ? _value2! : fallback;

    /// <summary>Gets the value at index 2 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2(Func<T2> factory) => _index == 2 ? _value2! : factory();

    /// <summary>Gets the value at index 2 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2<TState>(TState state, Func<TState, T2> factory) => _index == 2 ? _value2! : factory(state);

    /// <summary>Gets the value at index 3 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3(T3 fallback) => _index == 3 ? _value3! : fallback;

    /// <summary>Gets the value at index 3 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3(Func<T3> factory) => _index == 3 ? _value3! : factory();

    /// <summary>Gets the value at index 3 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3<TState>(TState state, Func<TState, T3> factory) => _index == 3 ? _value3! : factory(state);

    /// <summary>Gets the value at index 4 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T4 ValueOrT4(T4 fallback) => _index == 4 ? _value4! : fallback;

    /// <summary>Gets the value at index 4 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T4 ValueOrT4(Func<T4> factory) => _index == 4 ? _value4! : factory();

    /// <summary>Gets the value at index 4 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T4 ValueOrT4<TState>(TState state, Func<TState, T4> factory) => _index == 4 ? _value4! : factory(state);

    /// <summary>Gets the value at index 5 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T5 ValueOrT5(T5 fallback) => _index == 5 ? _value5! : fallback;

    /// <summary>Gets the value at index 5 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T5 ValueOrT5(Func<T5> factory) => _index == 5 ? _value5! : factory();

    /// <summary>Gets the value at index 5 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T5 ValueOrT5<TState>(TState state, Func<TState, T5> factory) => _index == 5 ? _value5! : factory(state);

    /// <summary>Gets the value at index 6 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T6 ValueOrT6(T6 fallback) => _index == 6 ? _value6! : fallback;

    /// <summary>Gets the value at index 6 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T6 ValueOrT6(Func<T6> factory) => _index == 6 ? _value6! : factory();

    /// <summary>Gets the value at index 6 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T6 ValueOrT6<TState>(TState state, Func<TState, T6> factory) => _index == 6 ? _value6! : factory(state);

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool Equals(Unio<T0, T1, T2, T3, T4, T5, T6> other) =>
        _index == other._index && _index switch
        {
            0 => EqualityComparer<T0>.Default.Equals(_value0, other._value0),
            1 => EqualityComparer<T1>.Default.Equals(_value1, other._value1),
            2 => EqualityComparer<T2>.Default.Equals(_value2, other._value2),
            3 => EqualityComparer<T3>.Default.Equals(_value3, other._value3),
            4 => EqualityComparer<T4>.Default.Equals(_value4, other._value4),
            5 => EqualityComparer<T5>.Default.Equals(_value5, other._value5),
            6 => EqualityComparer<T6>.Default.Equals(_value6, other._value6),
            _ => false
        };

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object? obj) => obj is Unio<T0, T1, T2, T3, T4, T5, T6> other && Equals(other);

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode()
    {
        unchecked
        {
            return (_index * 397) ^ (_index switch
            {
                0 => EqualityComparer<T0>.Default.GetHashCode(_value0!),
                1 => EqualityComparer<T1>.Default.GetHashCode(_value1!),
                2 => EqualityComparer<T2>.Default.GetHashCode(_value2!),
                3 => EqualityComparer<T3>.Default.GetHashCode(_value3!),
                4 => EqualityComparer<T4>.Default.GetHashCode(_value4!),
                5 => EqualityComparer<T5>.Default.GetHashCode(_value5!),
                6 => EqualityComparer<T6>.Default.GetHashCode(_value6!),
                _ => 0
            });
        }
    }

    /// <summary>Equality operator.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Unio<T0, T1, T2, T3, T4, T5, T6> left, Unio<T0, T1, T2, T3, T4, T5, T6> right) => left.Equals(right);

    /// <summary>Inequality operator.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Unio<T0, T1, T2, T3, T4, T5, T6> left, Unio<T0, T1, T2, T3, T4, T5, T6> right) => !left.Equals(right);

    /// <inheritdoc/>
    public override string ToString() => _index switch
    {
        0 => _value0?.ToString() ?? string.Empty,
        1 => _value1?.ToString() ?? string.Empty,
        2 => _value2?.ToString() ?? string.Empty,
        3 => _value3?.ToString() ?? string.Empty,
        4 => _value4?.ToString() ?? string.Empty,
        5 => _value5?.ToString() ?? string.Empty,
        6 => _value6?.ToString() ?? string.Empty,
        _ => string.Empty
    };

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => _index switch
    {
        0 => _value0 is IFormattable f0 ? f0.ToString(format, formatProvider) : _value0?.ToString() ?? string.Empty,
        1 => _value1 is IFormattable f1 ? f1.ToString(format, formatProvider) : _value1?.ToString() ?? string.Empty,
        2 => _value2 is IFormattable f2 ? f2.ToString(format, formatProvider) : _value2?.ToString() ?? string.Empty,
        3 => _value3 is IFormattable f3 ? f3.ToString(format, formatProvider) : _value3?.ToString() ?? string.Empty,
        4 => _value4 is IFormattable f4 ? f4.ToString(format, formatProvider) : _value4?.ToString() ?? string.Empty,
        5 => _value5 is IFormattable f5 ? f5.ToString(format, formatProvider) : _value5?.ToString() ?? string.Empty,
        6 => _value6 is IFormattable f6 ? f6.ToString(format, formatProvider) : _value6?.ToString() ?? string.Empty,
        _ => string.Empty
    };

    /// <inheritdoc/>
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        switch (_index)
        {
            case 0:
                if (_value0 is ISpanFormattable sf0) return sf0.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 1:
                if (_value1 is ISpanFormattable sf1) return sf1.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 2:
                if (_value2 is ISpanFormattable sf2) return sf2.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 3:
                if (_value3 is ISpanFormattable sf3) return sf3.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 4:
                if (_value4 is ISpanFormattable sf4) return sf4.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 5:
                if (_value5 is ISpanFormattable sf5) return sf5.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 6:
                if (_value6 is ISpanFormattable sf6) return sf6.TryFormat(destination, out charsWritten, format, provider);
                break;
        }
        string s = ToString();
        if (s.AsSpan().TryCopyTo(destination)) { charsWritten = s.Length; return true; }
        charsWritten = 0; return false;
    }

    /// <inheritdoc/>
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        switch (_index)
        {
            case 0:
                if (_value0 is IUtf8SpanFormattable uf0) return uf0.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 1:
                if (_value1 is IUtf8SpanFormattable uf1) return uf1.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 2:
                if (_value2 is IUtf8SpanFormattable uf2) return uf2.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 3:
                if (_value3 is IUtf8SpanFormattable uf3) return uf3.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 4:
                if (_value4 is IUtf8SpanFormattable uf4) return uf4.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 5:
                if (_value5 is IUtf8SpanFormattable uf5) return uf5.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 6:
                if (_value6 is IUtf8SpanFormattable uf6) return uf6.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
        }
        string s = ToString();
        int byteCount = System.Text.Encoding.UTF8.GetByteCount(s);
        if (byteCount <= utf8Destination.Length) { bytesWritten = System.Text.Encoding.UTF8.GetBytes(s, utf8Destination); return true; }
        bytesWritten = 0; return false;
    }
}
