// <auto-generated/>
// Copyright © BEN ABT (https://benjamin-abt.com) - all rights reserved

#nullable enable

namespace Unio;

/// <summary>
/// Represents a discriminated union that can hold exactly one of 4 possible types.
/// Implemented as a <c>readonly struct</c> with value semantics and zero heap allocation.
/// Use <c>UnioBase&lt;T0, T1, T2, T3&gt;</c> as a base class for named (class-based) union types.
/// </summary>
/// <typeparam name="T0">The type at index 0.</typeparam>
/// <typeparam name="T1">The type at index 1.</typeparam>
/// <typeparam name="T2">The type at index 2.</typeparam>
/// <typeparam name="T3">The type at index 3.</typeparam>
public readonly struct Unio<T0, T1, T2, T3> : IEquatable<Unio<T0, T1, T2, T3>>,
    IFormattable, ISpanFormattable, IUtf8SpanFormattable
{
    private readonly byte _index;
    private readonly T0? _value0;
    private readonly T1? _value1;
    private readonly T2? _value2;
    private readonly T3? _value3;

    private Unio(byte index, T0? value0 = default, T1? value1 = default, T2? value2 = default, T3? value3 = default)
    {
        _index = index;
        _value0 = value0;
        _value1 = value1;
        _value2 = value2;
        _value3 = value3;
    }

    /// <summary>Gets the zero-based index indicating which type is currently stored.</summary>
    public int Index
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T0"/>.</summary>
    public bool IsT0
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 0;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T1"/>.</summary>
    public bool IsT1
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 1;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T2"/>.</summary>
    public bool IsT2
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 2;
    }

    /// <summary>Returns true if the union currently holds a value of type <typeparamref name="T3"/>.</summary>
    public bool IsT3
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 3;
    }

    /// <summary>Gets the value as <typeparamref name="T0"/>. Throws if the union does not hold this type.</summary>
    public T0 AsT0
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 0 ? _value0! : throw new InvalidOperationException($"Cannot access T0 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T1"/>. Throws if the union does not hold this type.</summary>
    public T1 AsT1
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 1 ? _value1! : throw new InvalidOperationException($"Cannot access T1 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T2"/>. Throws if the union does not hold this type.</summary>
    public T2 AsT2
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 2 ? _value2! : throw new InvalidOperationException($"Cannot access T2 when the union holds T{_index}.");
    }

    /// <summary>Gets the value as <typeparamref name="T3"/>. Throws if the union does not hold this type.</summary>
    public T3 AsT3
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index == 3 ? _value3! : throw new InvalidOperationException($"Cannot access T3 when the union holds T{_index}.");
    }

    /// <summary>Gets the currently stored value as an object.</summary>
    public object Value
    {
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
    }

    /// <summary>Attempts to get the value as <typeparamref name="T0"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT0([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 value)
    {
        if (_index == 0) { value = _value0!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T1"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT1([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T1 value)
    {
        if (_index == 1) { value = _value1!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T2"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT2([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T2 value)
    {
        if (_index == 2) { value = _value2!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to get the value as <typeparamref name="T3"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryGetT3([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T3 value)
    {
        if (_index == 3) { value = _value3!; return true; }
        value = default; return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T0"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT0([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 value, out Unio<T1, T2, T3> remainder)
    {
        if (_index == 0) { value = _value0!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            1 => _value1!,
            2 => _value2!,
            3 => _value3!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T1"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT1([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T1 value, out Unio<T0, T2, T3> remainder)
    {
        if (_index == 1) { value = _value1!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            2 => _value2!,
            3 => _value3!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T2"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT2([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T2 value, out Unio<T0, T1, T3> remainder)
    {
        if (_index == 2) { value = _value2!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            3 => _value3!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Attempts to pick the value as <typeparamref name="T3"/> and returns the remaining union when it does not match.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool TryPickT3([System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T3 value, out Unio<T0, T1, T2> remainder)
    {
        if (_index == 3) { value = _value3!; remainder = default; return true; }
        value = default;
        remainder = _index switch
        {
            0 => _value0!,
            1 => _value1!,
            2 => _value2!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };
        return false;
    }

    /// <summary>Exhaustive match: applies the matching function based on the stored type and returns the result.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public TResult Match<TResult>(Func<T0, TResult> whenT0, Func<T1, TResult> whenT1, Func<T2, TResult> whenT2, Func<T3, TResult> whenT3) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive match with caller state to avoid delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public TResult Match<TState, TResult>(TState state, Func<TState, T0, TResult> whenT0, Func<TState, T1, TResult> whenT1, Func<TState, T2, TResult> whenT2, Func<TState, T3, TResult> whenT3) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive switch: executes the matching action based on the stored type.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Switch(Action<T0> whenT0, Action<T1> whenT1, Action<T2> whenT2, Action<T3> whenT3)
    {
        switch (_index)
        {
            case 0: whenT0(_value0!); break;
            case 1: whenT1(_value1!); break;
            case 2: whenT2(_value2!); break;
            case 3: whenT3(_value3!); break;
            default: throw new InvalidOperationException("Invalid union state.");
        }
    }

    /// <summary>Exhaustive switch with caller state to avoid delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void Switch<TState>(TState state, Action<TState, T0> whenT0, Action<TState, T1> whenT1, Action<TState, T2> whenT2, Action<TState, T3> whenT3)
    {
        switch (_index)
        {
            case 0: whenT0(state, _value0!); break;
            case 1: whenT1(state, _value1!); break;
            case 2: whenT2(state, _value2!); break;
            case 3: whenT3(state, _value3!); break;
            default: throw new InvalidOperationException("Invalid union state.");
        }
    }

    /// <summary>Exhaustive async match: applies the matching async function based on the stored type and returns the result.</summary>
    public ValueTask<TResult> Match<TResult>(Func<T0, ValueTask<TResult>> whenT0, Func<T1, ValueTask<TResult>> whenT1, Func<T2, ValueTask<TResult>> whenT2, Func<T3, ValueTask<TResult>> whenT3) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async match with caller state to avoid delegate captures in hot paths.</summary>
    public ValueTask<TResult> Match<TState, TResult>(TState state, Func<TState, T0, ValueTask<TResult>> whenT0, Func<TState, T1, ValueTask<TResult>> whenT1, Func<TState, T2, ValueTask<TResult>> whenT2, Func<TState, T3, ValueTask<TResult>> whenT3) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async switch: executes the matching async action based on the stored type.</summary>
    public ValueTask Switch(Func<T0, ValueTask> whenT0, Func<T1, ValueTask> whenT1, Func<T2, ValueTask> whenT2, Func<T3, ValueTask> whenT3) =>
        _index switch
        {
            0 => whenT0(_value0!),
            1 => whenT1(_value1!),
            2 => whenT2(_value2!),
            3 => whenT3(_value3!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Exhaustive async switch with caller state to avoid delegate captures in hot paths.</summary>
    public ValueTask Switch<TState>(TState state, Func<TState, T0, ValueTask> whenT0, Func<TState, T1, ValueTask> whenT1, Func<TState, T2, ValueTask> whenT2, Func<TState, T3, ValueTask> whenT3) =>
        _index switch
        {
            0 => whenT0(state, _value0!),
            1 => whenT1(state, _value1!),
            2 => whenT2(state, _value2!),
            3 => whenT3(state, _value3!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Creates a union holding a value of type <typeparamref name="T0"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3>(T0 value) => new(0, value0: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T1"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3>(T1 value) => new(1, value1: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T2"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3>(T2 value) => new(2, value2: value);

    /// <summary>Creates a union holding a value of type <typeparamref name="T3"/>.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static implicit operator Unio<T0, T1, T2, T3>(T3 value) => new(3, value3: value);

    /// <summary>Transforms the value at index 0 using the specified mapping function, returning a new union.</summary>
    public Unio<TNew, T1, T2, T3> MapT0<TNew>(Func<T0, TNew> map) =>
        _index switch
        {
            0 => (Unio<TNew, T1, T2, T3>)map(_value0!),
            1 => (Unio<TNew, T1, T2, T3>)_value1!,
            2 => (Unio<TNew, T1, T2, T3>)_value2!,
            3 => (Unio<TNew, T1, T2, T3>)_value3!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 1 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, TNew, T2, T3> MapT1<TNew>(Func<T1, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, TNew, T2, T3>)_value0!,
            1 => (Unio<T0, TNew, T2, T3>)map(_value1!),
            2 => (Unio<T0, TNew, T2, T3>)_value2!,
            3 => (Unio<T0, TNew, T2, T3>)_value3!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 2 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, TNew, T3> MapT2<TNew>(Func<T2, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, TNew, T3>)_value0!,
            1 => (Unio<T0, T1, TNew, T3>)_value1!,
            2 => (Unio<T0, T1, TNew, T3>)map(_value2!),
            3 => (Unio<T0, T1, TNew, T3>)_value3!,
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Transforms the value at index 3 using the specified mapping function, returning a new union.</summary>
    public Unio<T0, T1, T2, TNew> MapT3<TNew>(Func<T3, TNew> map) =>
        _index switch
        {
            0 => (Unio<T0, T1, T2, TNew>)_value0!,
            1 => (Unio<T0, T1, T2, TNew>)_value1!,
            2 => (Unio<T0, T1, T2, TNew>)_value2!,
            3 => (Unio<T0, T1, T2, TNew>)map(_value3!),
            _ => throw new InvalidOperationException("Invalid union state.")
        };

    /// <summary>Gets the value at index 0 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0(T0 fallback) => _index == 0 ? _value0! : fallback;

    /// <summary>Gets the value at index 0 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0(Func<T0> factory) => _index == 0 ? _value0! : factory();

    /// <summary>Gets the value at index 0 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T0 ValueOrT0<TState>(TState state, Func<TState, T0> factory) => _index == 0 ? _value0! : factory(state);

    /// <summary>Gets the value at index 1 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1(T1 fallback) => _index == 1 ? _value1! : fallback;

    /// <summary>Gets the value at index 1 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1(Func<T1> factory) => _index == 1 ? _value1! : factory();

    /// <summary>Gets the value at index 1 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T1 ValueOrT1<TState>(TState state, Func<TState, T1> factory) => _index == 1 ? _value1! : factory(state);

    /// <summary>Gets the value at index 2 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2(T2 fallback) => _index == 2 ? _value2! : fallback;

    /// <summary>Gets the value at index 2 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2(Func<T2> factory) => _index == 2 ? _value2! : factory();

    /// <summary>Gets the value at index 2 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T2 ValueOrT2<TState>(TState state, Func<TState, T2> factory) => _index == 2 ? _value2! : factory(state);

    /// <summary>Gets the value at index 3 or returns the specified fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3(T3 fallback) => _index == 3 ? _value3! : fallback;

    /// <summary>Gets the value at index 3 or invokes the factory to create a fallback.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3(Func<T3> factory) => _index == 3 ? _value3! : factory();

    /// <summary>Gets the value at index 3 or invokes the factory with caller state to create a fallback, avoiding delegate captures in hot paths.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public T3 ValueOrT3<TState>(TState state, Func<TState, T3> factory) => _index == 3 ? _value3! : factory(state);

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public bool Equals(Unio<T0, T1, T2, T3> other) =>
        _index == other._index && _index switch
        {
            0 => EqualityComparer<T0>.Default.Equals(_value0, other._value0),
            1 => EqualityComparer<T1>.Default.Equals(_value1, other._value1),
            2 => EqualityComparer<T2>.Default.Equals(_value2, other._value2),
            3 => EqualityComparer<T3>.Default.Equals(_value3, other._value3),
            _ => false
        };

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override bool Equals(object? obj) => obj is Unio<T0, T1, T2, T3> other && Equals(other);

    /// <inheritdoc/>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public override int GetHashCode()
    {
        unchecked
        {
            return (_index * 397) ^ (_index switch
            {
                0 => EqualityComparer<T0>.Default.GetHashCode(_value0!),
                1 => EqualityComparer<T1>.Default.GetHashCode(_value1!),
                2 => EqualityComparer<T2>.Default.GetHashCode(_value2!),
                3 => EqualityComparer<T3>.Default.GetHashCode(_value3!),
                _ => 0
            });
        }
    }

    /// <summary>Equality operator.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator ==(Unio<T0, T1, T2, T3> left, Unio<T0, T1, T2, T3> right) => left.Equals(right);

    /// <summary>Inequality operator.</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool operator !=(Unio<T0, T1, T2, T3> left, Unio<T0, T1, T2, T3> right) => !left.Equals(right);

    /// <inheritdoc/>
    public override string ToString() => _index switch
    {
        0 => _value0?.ToString() ?? string.Empty,
        1 => _value1?.ToString() ?? string.Empty,
        2 => _value2?.ToString() ?? string.Empty,
        3 => _value3?.ToString() ?? string.Empty,
        _ => string.Empty
    };

    /// <inheritdoc/>
    public string ToString(string? format, IFormatProvider? formatProvider) => _index switch
    {
        0 => _value0 is IFormattable f0 ? f0.ToString(format, formatProvider) : _value0?.ToString() ?? string.Empty,
        1 => _value1 is IFormattable f1 ? f1.ToString(format, formatProvider) : _value1?.ToString() ?? string.Empty,
        2 => _value2 is IFormattable f2 ? f2.ToString(format, formatProvider) : _value2?.ToString() ?? string.Empty,
        3 => _value3 is IFormattable f3 ? f3.ToString(format, formatProvider) : _value3?.ToString() ?? string.Empty,
        _ => string.Empty
    };

    /// <inheritdoc/>
    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        switch (_index)
        {
            case 0:
                if (_value0 is ISpanFormattable sf0) return sf0.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 1:
                if (_value1 is ISpanFormattable sf1) return sf1.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 2:
                if (_value2 is ISpanFormattable sf2) return sf2.TryFormat(destination, out charsWritten, format, provider);
                break;
            case 3:
                if (_value3 is ISpanFormattable sf3) return sf3.TryFormat(destination, out charsWritten, format, provider);
                break;
        }
        string s = ToString();
        if (s.AsSpan().TryCopyTo(destination)) { charsWritten = s.Length; return true; }
        charsWritten = 0; return false;
    }

    /// <inheritdoc/>
    public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
    {
        switch (_index)
        {
            case 0:
                if (_value0 is IUtf8SpanFormattable uf0) return uf0.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 1:
                if (_value1 is IUtf8SpanFormattable uf1) return uf1.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 2:
                if (_value2 is IUtf8SpanFormattable uf2) return uf2.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
            case 3:
                if (_value3 is IUtf8SpanFormattable uf3) return uf3.TryFormat(utf8Destination, out bytesWritten, format, provider);
                break;
        }
        string s = ToString();
        int byteCount = System.Text.Encoding.UTF8.GetByteCount(s);
        if (byteCount <= utf8Destination.Length) { bytesWritten = System.Text.Encoding.UTF8.GetBytes(s, utf8Destination); return true; }
        bytesWritten = 0; return false;
    }
}
