<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <VerifyReferenceAotCompatibility Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">true</VerifyReferenceAotCompatibility>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Unio/Unio.csproj" />
    <ProjectReference Include="../../src/Unio.Types/Unio.Types.csproj" />
    <ProjectReference Include="../../src/Unio.Extensions/Unio.Extensions.csproj" />
    <ProjectReference Include="../../src/Unio.SourceGenerator/Unio.SourceGenerator.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

  </ItemGroup>

</Project>
